// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/security/api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetEventParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventParams) Reset()         { *m = GetEventParams{} }
func (m *GetEventParams) String() string { return proto.CompactTextString(m) }
func (*GetEventParams) ProtoMessage()    {}
func (*GetEventParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{0}
}

func (m *GetEventParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventParams.Unmarshal(m, b)
}
func (m *GetEventParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventParams.Marshal(b, m, deterministic)
}
func (m *GetEventParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventParams.Merge(m, src)
}
func (m *GetEventParams) XXX_Size() int {
	return xxx_messageInfo_GetEventParams.Size(m)
}
func (m *GetEventParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventParams proto.InternalMessageInfo

type SecurityEventMessage struct {
	RuleID               string   `protobuf:"bytes,1,opt,name=RuleID,proto3" json:"RuleID,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Service              string   `protobuf:"bytes,4,opt,name=Service,proto3" json:"Service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityEventMessage) Reset()         { *m = SecurityEventMessage{} }
func (m *SecurityEventMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityEventMessage) ProtoMessage()    {}
func (*SecurityEventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{1}
}

func (m *SecurityEventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityEventMessage.Unmarshal(m, b)
}
func (m *SecurityEventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityEventMessage.Marshal(b, m, deterministic)
}
func (m *SecurityEventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityEventMessage.Merge(m, src)
}
func (m *SecurityEventMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityEventMessage.Size(m)
}
func (m *SecurityEventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityEventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityEventMessage proto.InternalMessageInfo

func (m *SecurityEventMessage) GetRuleID() string {
	if m != nil {
		return m.RuleID
	}
	return ""
}

func (m *SecurityEventMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SecurityEventMessage) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SecurityEventMessage) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type GetProcessEventParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProcessEventParams) Reset()         { *m = GetProcessEventParams{} }
func (m *GetProcessEventParams) String() string { return proto.CompactTextString(m) }
func (*GetProcessEventParams) ProtoMessage()    {}
func (*GetProcessEventParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{2}
}

func (m *GetProcessEventParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProcessEventParams.Unmarshal(m, b)
}
func (m *GetProcessEventParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProcessEventParams.Marshal(b, m, deterministic)
}
func (m *GetProcessEventParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProcessEventParams.Merge(m, src)
}
func (m *GetProcessEventParams) XXX_Size() int {
	return xxx_messageInfo_GetProcessEventParams.Size(m)
}
func (m *GetProcessEventParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProcessEventParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetProcessEventParams proto.InternalMessageInfo

type SecurityProcessEventMessage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityProcessEventMessage) Reset()         { *m = SecurityProcessEventMessage{} }
func (m *SecurityProcessEventMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityProcessEventMessage) ProtoMessage()    {}
func (*SecurityProcessEventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{3}
}

func (m *SecurityProcessEventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityProcessEventMessage.Unmarshal(m, b)
}
func (m *SecurityProcessEventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityProcessEventMessage.Marshal(b, m, deterministic)
}
func (m *SecurityProcessEventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityProcessEventMessage.Merge(m, src)
}
func (m *SecurityProcessEventMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityProcessEventMessage.Size(m)
}
func (m *SecurityProcessEventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityProcessEventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityProcessEventMessage proto.InternalMessageInfo

func (m *SecurityProcessEventMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DumpProcessCacheParams struct {
	WithArgs             bool     `protobuf:"varint,1,opt,name=WithArgs,proto3" json:"WithArgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpProcessCacheParams) Reset()         { *m = DumpProcessCacheParams{} }
func (m *DumpProcessCacheParams) String() string { return proto.CompactTextString(m) }
func (*DumpProcessCacheParams) ProtoMessage()    {}
func (*DumpProcessCacheParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{4}
}

func (m *DumpProcessCacheParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpProcessCacheParams.Unmarshal(m, b)
}
func (m *DumpProcessCacheParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpProcessCacheParams.Marshal(b, m, deterministic)
}
func (m *DumpProcessCacheParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpProcessCacheParams.Merge(m, src)
}
func (m *DumpProcessCacheParams) XXX_Size() int {
	return xxx_messageInfo_DumpProcessCacheParams.Size(m)
}
func (m *DumpProcessCacheParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpProcessCacheParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpProcessCacheParams proto.InternalMessageInfo

func (m *DumpProcessCacheParams) GetWithArgs() bool {
	if m != nil {
		return m.WithArgs
	}
	return false
}

type SecurityDumpProcessCacheMessage struct {
	Filename             string   `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityDumpProcessCacheMessage) Reset()         { *m = SecurityDumpProcessCacheMessage{} }
func (m *SecurityDumpProcessCacheMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityDumpProcessCacheMessage) ProtoMessage()    {}
func (*SecurityDumpProcessCacheMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{5}
}

func (m *SecurityDumpProcessCacheMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Unmarshal(m, b)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Marshal(b, m, deterministic)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityDumpProcessCacheMessage.Merge(m, src)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Size(m)
}
func (m *SecurityDumpProcessCacheMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityDumpProcessCacheMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityDumpProcessCacheMessage proto.InternalMessageInfo

func (m *SecurityDumpProcessCacheMessage) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type DumpNetworkNamespaceParams struct {
	SnapshotInterfaces   bool     `protobuf:"varint,1,opt,name=SnapshotInterfaces,proto3" json:"SnapshotInterfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpNetworkNamespaceParams) Reset()         { *m = DumpNetworkNamespaceParams{} }
func (m *DumpNetworkNamespaceParams) String() string { return proto.CompactTextString(m) }
func (*DumpNetworkNamespaceParams) ProtoMessage()    {}
func (*DumpNetworkNamespaceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{6}
}

func (m *DumpNetworkNamespaceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Unmarshal(m, b)
}
func (m *DumpNetworkNamespaceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Marshal(b, m, deterministic)
}
func (m *DumpNetworkNamespaceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpNetworkNamespaceParams.Merge(m, src)
}
func (m *DumpNetworkNamespaceParams) XXX_Size() int {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Size(m)
}
func (m *DumpNetworkNamespaceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpNetworkNamespaceParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpNetworkNamespaceParams proto.InternalMessageInfo

func (m *DumpNetworkNamespaceParams) GetSnapshotInterfaces() bool {
	if m != nil {
		return m.SnapshotInterfaces
	}
	return false
}

type DumpNetworkNamespaceMessage struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	DumpFilename         string   `protobuf:"bytes,2,opt,name=DumpFilename,proto3" json:"DumpFilename,omitempty"`
	GraphFilename        string   `protobuf:"bytes,3,opt,name=GraphFilename,proto3" json:"GraphFilename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpNetworkNamespaceMessage) Reset()         { *m = DumpNetworkNamespaceMessage{} }
func (m *DumpNetworkNamespaceMessage) String() string { return proto.CompactTextString(m) }
func (*DumpNetworkNamespaceMessage) ProtoMessage()    {}
func (*DumpNetworkNamespaceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{7}
}

func (m *DumpNetworkNamespaceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Unmarshal(m, b)
}
func (m *DumpNetworkNamespaceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Marshal(b, m, deterministic)
}
func (m *DumpNetworkNamespaceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpNetworkNamespaceMessage.Merge(m, src)
}
func (m *DumpNetworkNamespaceMessage) XXX_Size() int {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Size(m)
}
func (m *DumpNetworkNamespaceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpNetworkNamespaceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DumpNetworkNamespaceMessage proto.InternalMessageInfo

func (m *DumpNetworkNamespaceMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DumpNetworkNamespaceMessage) GetDumpFilename() string {
	if m != nil {
		return m.DumpFilename
	}
	return ""
}

func (m *DumpNetworkNamespaceMessage) GetGraphFilename() string {
	if m != nil {
		return m.GraphFilename
	}
	return ""
}

type GetConfigParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigParams) Reset()         { *m = GetConfigParams{} }
func (m *GetConfigParams) String() string { return proto.CompactTextString(m) }
func (*GetConfigParams) ProtoMessage()    {}
func (*GetConfigParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{8}
}

func (m *GetConfigParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigParams.Unmarshal(m, b)
}
func (m *GetConfigParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigParams.Marshal(b, m, deterministic)
}
func (m *GetConfigParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigParams.Merge(m, src)
}
func (m *GetConfigParams) XXX_Size() int {
	return xxx_messageInfo_GetConfigParams.Size(m)
}
func (m *GetConfigParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigParams proto.InternalMessageInfo

type SecurityConfigMessage struct {
	RuntimeEnabled       bool     `protobuf:"varint,1,opt,name=RuntimeEnabled,proto3" json:"RuntimeEnabled,omitempty"`
	FIMEnabled           bool     `protobuf:"varint,2,opt,name=FIMEnabled,proto3" json:"FIMEnabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityConfigMessage) Reset()         { *m = SecurityConfigMessage{} }
func (m *SecurityConfigMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityConfigMessage) ProtoMessage()    {}
func (*SecurityConfigMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{9}
}

func (m *SecurityConfigMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityConfigMessage.Unmarshal(m, b)
}
func (m *SecurityConfigMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityConfigMessage.Marshal(b, m, deterministic)
}
func (m *SecurityConfigMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityConfigMessage.Merge(m, src)
}
func (m *SecurityConfigMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityConfigMessage.Size(m)
}
func (m *SecurityConfigMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityConfigMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityConfigMessage proto.InternalMessageInfo

func (m *SecurityConfigMessage) GetRuntimeEnabled() bool {
	if m != nil {
		return m.RuntimeEnabled
	}
	return false
}

func (m *SecurityConfigMessage) GetFIMEnabled() bool {
	if m != nil {
		return m.FIMEnabled
	}
	return false
}

type RunSelfTestParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunSelfTestParams) Reset()         { *m = RunSelfTestParams{} }
func (m *RunSelfTestParams) String() string { return proto.CompactTextString(m) }
func (*RunSelfTestParams) ProtoMessage()    {}
func (*RunSelfTestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{10}
}

func (m *RunSelfTestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSelfTestParams.Unmarshal(m, b)
}
func (m *RunSelfTestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSelfTestParams.Marshal(b, m, deterministic)
}
func (m *RunSelfTestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSelfTestParams.Merge(m, src)
}
func (m *RunSelfTestParams) XXX_Size() int {
	return xxx_messageInfo_RunSelfTestParams.Size(m)
}
func (m *RunSelfTestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSelfTestParams.DiscardUnknown(m)
}

var xxx_messageInfo_RunSelfTestParams proto.InternalMessageInfo

type ReloadPoliciesParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadPoliciesParams) Reset()         { *m = ReloadPoliciesParams{} }
func (m *ReloadPoliciesParams) String() string { return proto.CompactTextString(m) }
func (*ReloadPoliciesParams) ProtoMessage()    {}
func (*ReloadPoliciesParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{11}
}

func (m *ReloadPoliciesParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadPoliciesParams.Unmarshal(m, b)
}
func (m *ReloadPoliciesParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadPoliciesParams.Marshal(b, m, deterministic)
}
func (m *ReloadPoliciesParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadPoliciesParams.Merge(m, src)
}
func (m *ReloadPoliciesParams) XXX_Size() int {
	return xxx_messageInfo_ReloadPoliciesParams.Size(m)
}
func (m *ReloadPoliciesParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadPoliciesParams.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadPoliciesParams proto.InternalMessageInfo

type ReloadPoliciesResultMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadPoliciesResultMessage) Reset()         { *m = ReloadPoliciesResultMessage{} }
func (m *ReloadPoliciesResultMessage) String() string { return proto.CompactTextString(m) }
func (*ReloadPoliciesResultMessage) ProtoMessage()    {}
func (*ReloadPoliciesResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{12}
}

func (m *ReloadPoliciesResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Unmarshal(m, b)
}
func (m *ReloadPoliciesResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Marshal(b, m, deterministic)
}
func (m *ReloadPoliciesResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadPoliciesResultMessage.Merge(m, src)
}
func (m *ReloadPoliciesResultMessage) XXX_Size() int {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Size(m)
}
func (m *ReloadPoliciesResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadPoliciesResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadPoliciesResultMessage proto.InternalMessageInfo

type SecuritySelfTestResultMessage struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecuritySelfTestResultMessage) Reset()         { *m = SecuritySelfTestResultMessage{} }
func (m *SecuritySelfTestResultMessage) String() string { return proto.CompactTextString(m) }
func (*SecuritySelfTestResultMessage) ProtoMessage()    {}
func (*SecuritySelfTestResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{13}
}

func (m *SecuritySelfTestResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Unmarshal(m, b)
}
func (m *SecuritySelfTestResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Marshal(b, m, deterministic)
}
func (m *SecuritySelfTestResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecuritySelfTestResultMessage.Merge(m, src)
}
func (m *SecuritySelfTestResultMessage) XXX_Size() int {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Size(m)
}
func (m *SecuritySelfTestResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecuritySelfTestResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecuritySelfTestResultMessage proto.InternalMessageInfo

func (m *SecuritySelfTestResultMessage) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SecuritySelfTestResultMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DumpActivityParams struct {
	Comm                 string   `protobuf:"bytes,1,opt,name=comm,proto3" json:"comm,omitempty"`
	Timeout              int32    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	WithGraph            bool     `protobuf:"varint,3,opt,name=WithGraph,proto3" json:"WithGraph,omitempty"`
	DifferentiateArgs    bool     `protobuf:"varint,4,opt,name=DifferentiateArgs,proto3" json:"DifferentiateArgs,omitempty"`
	OutputDirectory      string   `protobuf:"bytes,5,opt,name=OutputDirectory,proto3" json:"OutputDirectory,omitempty"`
	OutputFormat         string   `protobuf:"bytes,6,opt,name=OutputFormat,proto3" json:"OutputFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpActivityParams) Reset()         { *m = DumpActivityParams{} }
func (m *DumpActivityParams) String() string { return proto.CompactTextString(m) }
func (*DumpActivityParams) ProtoMessage()    {}
func (*DumpActivityParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{14}
}

func (m *DumpActivityParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpActivityParams.Unmarshal(m, b)
}
func (m *DumpActivityParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpActivityParams.Marshal(b, m, deterministic)
}
func (m *DumpActivityParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpActivityParams.Merge(m, src)
}
func (m *DumpActivityParams) XXX_Size() int {
	return xxx_messageInfo_DumpActivityParams.Size(m)
}
func (m *DumpActivityParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpActivityParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpActivityParams proto.InternalMessageInfo

func (m *DumpActivityParams) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

func (m *DumpActivityParams) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *DumpActivityParams) GetWithGraph() bool {
	if m != nil {
		return m.WithGraph
	}
	return false
}

func (m *DumpActivityParams) GetDifferentiateArgs() bool {
	if m != nil {
		return m.DifferentiateArgs
	}
	return false
}

func (m *DumpActivityParams) GetOutputDirectory() string {
	if m != nil {
		return m.OutputDirectory
	}
	return ""
}

func (m *DumpActivityParams) GetOutputFormat() string {
	if m != nil {
		return m.OutputFormat
	}
	return ""
}

type SecurityActivityDumpMessage struct {
	OutputFilename       string   `protobuf:"bytes,1,opt,name=OutputFilename,proto3" json:"OutputFilename,omitempty"`
	GraphFilename        string   `protobuf:"bytes,2,opt,name=GraphFilename,proto3" json:"GraphFilename,omitempty"`
	Comm                 string   `protobuf:"bytes,3,opt,name=Comm,proto3" json:"Comm,omitempty"`
	ContainerID          string   `protobuf:"bytes,4,opt,name=ContainerID,proto3" json:"ContainerID,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	WithGraph            bool     `protobuf:"varint,6,opt,name=WithGraph,proto3" json:"WithGraph,omitempty"`
	DifferentiateArgs    bool     `protobuf:"varint,7,opt,name=DifferentiateArgs,proto3" json:"DifferentiateArgs,omitempty"`
	Timeout              string   `protobuf:"bytes,8,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Start                string   `protobuf:"bytes,9,opt,name=Start,proto3" json:"Start,omitempty"`
	Left                 string   `protobuf:"bytes,10,opt,name=Left,proto3" json:"Left,omitempty"`
	Error                string   `protobuf:"bytes,11,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityActivityDumpMessage) Reset()         { *m = SecurityActivityDumpMessage{} }
func (m *SecurityActivityDumpMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpMessage) ProtoMessage()    {}
func (*SecurityActivityDumpMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{15}
}

func (m *SecurityActivityDumpMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpMessage.Merge(m, src)
}
func (m *SecurityActivityDumpMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpMessage.Size(m)
}
func (m *SecurityActivityDumpMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpMessage) GetOutputFilename() string {
	if m != nil {
		return m.OutputFilename
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetGraphFilename() string {
	if m != nil {
		return m.GraphFilename
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SecurityActivityDumpMessage) GetWithGraph() bool {
	if m != nil {
		return m.WithGraph
	}
	return false
}

func (m *SecurityActivityDumpMessage) GetDifferentiateArgs() bool {
	if m != nil {
		return m.DifferentiateArgs
	}
	return false
}

func (m *SecurityActivityDumpMessage) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetLeft() string {
	if m != nil {
		return m.Left
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListActivityDumpsParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActivityDumpsParams) Reset()         { *m = ListActivityDumpsParams{} }
func (m *ListActivityDumpsParams) String() string { return proto.CompactTextString(m) }
func (*ListActivityDumpsParams) ProtoMessage()    {}
func (*ListActivityDumpsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{16}
}

func (m *ListActivityDumpsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivityDumpsParams.Unmarshal(m, b)
}
func (m *ListActivityDumpsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivityDumpsParams.Marshal(b, m, deterministic)
}
func (m *ListActivityDumpsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivityDumpsParams.Merge(m, src)
}
func (m *ListActivityDumpsParams) XXX_Size() int {
	return xxx_messageInfo_ListActivityDumpsParams.Size(m)
}
func (m *ListActivityDumpsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivityDumpsParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivityDumpsParams proto.InternalMessageInfo

type SecurityActivityDumpListMessage struct {
	Dumps                []*SecurityActivityDumpMessage `protobuf:"bytes,1,rep,name=Dumps,proto3" json:"Dumps,omitempty"`
	Error                string                         `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SecurityActivityDumpListMessage) Reset()         { *m = SecurityActivityDumpListMessage{} }
func (m *SecurityActivityDumpListMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpListMessage) ProtoMessage()    {}
func (*SecurityActivityDumpListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{17}
}

func (m *SecurityActivityDumpListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpListMessage.Merge(m, src)
}
func (m *SecurityActivityDumpListMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Size(m)
}
func (m *SecurityActivityDumpListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpListMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpListMessage) GetDumps() []*SecurityActivityDumpMessage {
	if m != nil {
		return m.Dumps
	}
	return nil
}

func (m *SecurityActivityDumpListMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type StopActivityDumpParams struct {
	Comm                 string   `protobuf:"bytes,2,opt,name=Comm,proto3" json:"Comm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopActivityDumpParams) Reset()         { *m = StopActivityDumpParams{} }
func (m *StopActivityDumpParams) String() string { return proto.CompactTextString(m) }
func (*StopActivityDumpParams) ProtoMessage()    {}
func (*StopActivityDumpParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{18}
}

func (m *StopActivityDumpParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopActivityDumpParams.Unmarshal(m, b)
}
func (m *StopActivityDumpParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopActivityDumpParams.Marshal(b, m, deterministic)
}
func (m *StopActivityDumpParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopActivityDumpParams.Merge(m, src)
}
func (m *StopActivityDumpParams) XXX_Size() int {
	return xxx_messageInfo_StopActivityDumpParams.Size(m)
}
func (m *StopActivityDumpParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StopActivityDumpParams.DiscardUnknown(m)
}

var xxx_messageInfo_StopActivityDumpParams proto.InternalMessageInfo

func (m *StopActivityDumpParams) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

type SecurityActivityDumpStoppedMessage struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityActivityDumpStoppedMessage) Reset()         { *m = SecurityActivityDumpStoppedMessage{} }
func (m *SecurityActivityDumpStoppedMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpStoppedMessage) ProtoMessage()    {}
func (*SecurityActivityDumpStoppedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{19}
}

func (m *SecurityActivityDumpStoppedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpStoppedMessage.Merge(m, src)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Size(m)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpStoppedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpStoppedMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpStoppedMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GenerateProfileParams struct {
	ActivityDumpFile     string   `protobuf:"bytes,1,opt,name=ActivityDumpFile,proto3" json:"ActivityDumpFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateProfileParams) Reset()         { *m = GenerateProfileParams{} }
func (m *GenerateProfileParams) String() string { return proto.CompactTextString(m) }
func (*GenerateProfileParams) ProtoMessage()    {}
func (*GenerateProfileParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{20}
}

func (m *GenerateProfileParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateProfileParams.Unmarshal(m, b)
}
func (m *GenerateProfileParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateProfileParams.Marshal(b, m, deterministic)
}
func (m *GenerateProfileParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateProfileParams.Merge(m, src)
}
func (m *GenerateProfileParams) XXX_Size() int {
	return xxx_messageInfo_GenerateProfileParams.Size(m)
}
func (m *GenerateProfileParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateProfileParams.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateProfileParams proto.InternalMessageInfo

func (m *GenerateProfileParams) GetActivityDumpFile() string {
	if m != nil {
		return m.ActivityDumpFile
	}
	return ""
}

type SecurityProfileGeneratedMessage struct {
	ProfilePath          string   `protobuf:"bytes,1,opt,name=ProfilePath,proto3" json:"ProfilePath,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityProfileGeneratedMessage) Reset()         { *m = SecurityProfileGeneratedMessage{} }
func (m *SecurityProfileGeneratedMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityProfileGeneratedMessage) ProtoMessage()    {}
func (*SecurityProfileGeneratedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{21}
}

func (m *SecurityProfileGeneratedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityProfileGeneratedMessage.Unmarshal(m, b)
}
func (m *SecurityProfileGeneratedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityProfileGeneratedMessage.Marshal(b, m, deterministic)
}
func (m *SecurityProfileGeneratedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityProfileGeneratedMessage.Merge(m, src)
}
func (m *SecurityProfileGeneratedMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityProfileGeneratedMessage.Size(m)
}
func (m *SecurityProfileGeneratedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityProfileGeneratedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityProfileGeneratedMessage proto.InternalMessageInfo

func (m *SecurityProfileGeneratedMessage) GetProfilePath() string {
	if m != nil {
		return m.ProfilePath
	}
	return ""
}

func (m *SecurityProfileGeneratedMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GenerateGraphParams struct {
	ActivityDumpFile     string   `protobuf:"bytes,1,opt,name=ActivityDumpFile,proto3" json:"ActivityDumpFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateGraphParams) Reset()         { *m = GenerateGraphParams{} }
func (m *GenerateGraphParams) String() string { return proto.CompactTextString(m) }
func (*GenerateGraphParams) ProtoMessage()    {}
func (*GenerateGraphParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{22}
}

func (m *GenerateGraphParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateGraphParams.Unmarshal(m, b)
}
func (m *GenerateGraphParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateGraphParams.Marshal(b, m, deterministic)
}
func (m *GenerateGraphParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateGraphParams.Merge(m, src)
}
func (m *GenerateGraphParams) XXX_Size() int {
	return xxx_messageInfo_GenerateGraphParams.Size(m)
}
func (m *GenerateGraphParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateGraphParams.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateGraphParams proto.InternalMessageInfo

func (m *GenerateGraphParams) GetActivityDumpFile() string {
	if m != nil {
		return m.ActivityDumpFile
	}
	return ""
}

type SecurityGraphGeneratedMessage struct {
	GraphPath            string   `protobuf:"bytes,1,opt,name=GraphPath,proto3" json:"GraphPath,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityGraphGeneratedMessage) Reset()         { *m = SecurityGraphGeneratedMessage{} }
func (m *SecurityGraphGeneratedMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityGraphGeneratedMessage) ProtoMessage()    {}
func (*SecurityGraphGeneratedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{23}
}

func (m *SecurityGraphGeneratedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityGraphGeneratedMessage.Unmarshal(m, b)
}
func (m *SecurityGraphGeneratedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityGraphGeneratedMessage.Marshal(b, m, deterministic)
}
func (m *SecurityGraphGeneratedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityGraphGeneratedMessage.Merge(m, src)
}
func (m *SecurityGraphGeneratedMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityGraphGeneratedMessage.Size(m)
}
func (m *SecurityGraphGeneratedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityGraphGeneratedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityGraphGeneratedMessage proto.InternalMessageInfo

func (m *SecurityGraphGeneratedMessage) GetGraphPath() string {
	if m != nil {
		return m.GraphPath
	}
	return ""
}

func (m *SecurityGraphGeneratedMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetStatusParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusParams) Reset()         { *m = GetStatusParams{} }
func (m *GetStatusParams) String() string { return proto.CompactTextString(m) }
func (*GetStatusParams) ProtoMessage()    {}
func (*GetStatusParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{24}
}

func (m *GetStatusParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusParams.Unmarshal(m, b)
}
func (m *GetStatusParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusParams.Marshal(b, m, deterministic)
}
func (m *GetStatusParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusParams.Merge(m, src)
}
func (m *GetStatusParams) XXX_Size() int {
	return xxx_messageInfo_GetStatusParams.Size(m)
}
func (m *GetStatusParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusParams proto.InternalMessageInfo

type ConstantValueAndSource struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value                uint64   `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstantValueAndSource) Reset()         { *m = ConstantValueAndSource{} }
func (m *ConstantValueAndSource) String() string { return proto.CompactTextString(m) }
func (*ConstantValueAndSource) ProtoMessage()    {}
func (*ConstantValueAndSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{25}
}

func (m *ConstantValueAndSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstantValueAndSource.Unmarshal(m, b)
}
func (m *ConstantValueAndSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstantValueAndSource.Marshal(b, m, deterministic)
}
func (m *ConstantValueAndSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstantValueAndSource.Merge(m, src)
}
func (m *ConstantValueAndSource) XXX_Size() int {
	return xxx_messageInfo_ConstantValueAndSource.Size(m)
}
func (m *ConstantValueAndSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstantValueAndSource.DiscardUnknown(m)
}

var xxx_messageInfo_ConstantValueAndSource proto.InternalMessageInfo

func (m *ConstantValueAndSource) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ConstantValueAndSource) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ConstantValueAndSource) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type SelfTestsStatus struct {
	LastTimestamp        string   `protobuf:"bytes,1,opt,name=LastTimestamp,proto3" json:"LastTimestamp,omitempty"`
	Success              []string `protobuf:"bytes,2,rep,name=Success,proto3" json:"Success,omitempty"`
	Fails                []string `protobuf:"bytes,3,rep,name=Fails,proto3" json:"Fails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfTestsStatus) Reset()         { *m = SelfTestsStatus{} }
func (m *SelfTestsStatus) String() string { return proto.CompactTextString(m) }
func (*SelfTestsStatus) ProtoMessage()    {}
func (*SelfTestsStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{26}
}

func (m *SelfTestsStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfTestsStatus.Unmarshal(m, b)
}
func (m *SelfTestsStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfTestsStatus.Marshal(b, m, deterministic)
}
func (m *SelfTestsStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfTestsStatus.Merge(m, src)
}
func (m *SelfTestsStatus) XXX_Size() int {
	return xxx_messageInfo_SelfTestsStatus.Size(m)
}
func (m *SelfTestsStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfTestsStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SelfTestsStatus proto.InternalMessageInfo

func (m *SelfTestsStatus) GetLastTimestamp() string {
	if m != nil {
		return m.LastTimestamp
	}
	return ""
}

func (m *SelfTestsStatus) GetSuccess() []string {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *SelfTestsStatus) GetFails() []string {
	if m != nil {
		return m.Fails
	}
	return nil
}

type Status struct {
	Environment          *EnvironmentStatus `protobuf:"bytes,1,opt,name=Environment,proto3" json:"Environment,omitempty"`
	SelfTests            *SelfTestsStatus   `protobuf:"bytes,2,opt,name=SelfTests,proto3" json:"SelfTests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{27}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetEnvironment() *EnvironmentStatus {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *Status) GetSelfTests() *SelfTestsStatus {
	if m != nil {
		return m.SelfTests
	}
	return nil
}

type ConstantFetcherStatus struct {
	Fetchers             []string                  `protobuf:"bytes,1,rep,name=Fetchers,proto3" json:"Fetchers,omitempty"`
	Values               []*ConstantValueAndSource `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConstantFetcherStatus) Reset()         { *m = ConstantFetcherStatus{} }
func (m *ConstantFetcherStatus) String() string { return proto.CompactTextString(m) }
func (*ConstantFetcherStatus) ProtoMessage()    {}
func (*ConstantFetcherStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{28}
}

func (m *ConstantFetcherStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstantFetcherStatus.Unmarshal(m, b)
}
func (m *ConstantFetcherStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstantFetcherStatus.Marshal(b, m, deterministic)
}
func (m *ConstantFetcherStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstantFetcherStatus.Merge(m, src)
}
func (m *ConstantFetcherStatus) XXX_Size() int {
	return xxx_messageInfo_ConstantFetcherStatus.Size(m)
}
func (m *ConstantFetcherStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstantFetcherStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ConstantFetcherStatus proto.InternalMessageInfo

func (m *ConstantFetcherStatus) GetFetchers() []string {
	if m != nil {
		return m.Fetchers
	}
	return nil
}

func (m *ConstantFetcherStatus) GetValues() []*ConstantValueAndSource {
	if m != nil {
		return m.Values
	}
	return nil
}

type EnvironmentStatus struct {
	Warnings             []string               `protobuf:"bytes,1,rep,name=Warnings,proto3" json:"Warnings,omitempty"`
	Constants            *ConstantFetcherStatus `protobuf:"bytes,2,opt,name=Constants,proto3" json:"Constants,omitempty"`
	KernelLockdown       string                 `protobuf:"bytes,3,opt,name=KernelLockdown,proto3" json:"KernelLockdown,omitempty"`
	UseMmapableMaps      bool                   `protobuf:"varint,4,opt,name=UseMmapableMaps,proto3" json:"UseMmapableMaps,omitempty"`
	UseRingBuffer        bool                   `protobuf:"varint,5,opt,name=UseRingBuffer,proto3" json:"UseRingBuffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EnvironmentStatus) Reset()         { *m = EnvironmentStatus{} }
func (m *EnvironmentStatus) String() string { return proto.CompactTextString(m) }
func (*EnvironmentStatus) ProtoMessage()    {}
func (*EnvironmentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{29}
}

func (m *EnvironmentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentStatus.Unmarshal(m, b)
}
func (m *EnvironmentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentStatus.Marshal(b, m, deterministic)
}
func (m *EnvironmentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentStatus.Merge(m, src)
}
func (m *EnvironmentStatus) XXX_Size() int {
	return xxx_messageInfo_EnvironmentStatus.Size(m)
}
func (m *EnvironmentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentStatus proto.InternalMessageInfo

func (m *EnvironmentStatus) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *EnvironmentStatus) GetConstants() *ConstantFetcherStatus {
	if m != nil {
		return m.Constants
	}
	return nil
}

func (m *EnvironmentStatus) GetKernelLockdown() string {
	if m != nil {
		return m.KernelLockdown
	}
	return ""
}

func (m *EnvironmentStatus) GetUseMmapableMaps() bool {
	if m != nil {
		return m.UseMmapableMaps
	}
	return false
}

func (m *EnvironmentStatus) GetUseRingBuffer() bool {
	if m != nil {
		return m.UseRingBuffer
	}
	return false
}

func init() {
	proto.RegisterType((*GetEventParams)(nil), "api.GetEventParams")
	proto.RegisterType((*SecurityEventMessage)(nil), "api.SecurityEventMessage")
	proto.RegisterType((*GetProcessEventParams)(nil), "api.GetProcessEventParams")
	proto.RegisterType((*SecurityProcessEventMessage)(nil), "api.SecurityProcessEventMessage")
	proto.RegisterType((*DumpProcessCacheParams)(nil), "api.DumpProcessCacheParams")
	proto.RegisterType((*SecurityDumpProcessCacheMessage)(nil), "api.SecurityDumpProcessCacheMessage")
	proto.RegisterType((*DumpNetworkNamespaceParams)(nil), "api.DumpNetworkNamespaceParams")
	proto.RegisterType((*DumpNetworkNamespaceMessage)(nil), "api.DumpNetworkNamespaceMessage")
	proto.RegisterType((*GetConfigParams)(nil), "api.GetConfigParams")
	proto.RegisterType((*SecurityConfigMessage)(nil), "api.SecurityConfigMessage")
	proto.RegisterType((*RunSelfTestParams)(nil), "api.RunSelfTestParams")
	proto.RegisterType((*ReloadPoliciesParams)(nil), "api.ReloadPoliciesParams")
	proto.RegisterType((*ReloadPoliciesResultMessage)(nil), "api.ReloadPoliciesResultMessage")
	proto.RegisterType((*SecuritySelfTestResultMessage)(nil), "api.SecuritySelfTestResultMessage")
	proto.RegisterType((*DumpActivityParams)(nil), "api.DumpActivityParams")
	proto.RegisterType((*SecurityActivityDumpMessage)(nil), "api.SecurityActivityDumpMessage")
	proto.RegisterType((*ListActivityDumpsParams)(nil), "api.ListActivityDumpsParams")
	proto.RegisterType((*SecurityActivityDumpListMessage)(nil), "api.SecurityActivityDumpListMessage")
	proto.RegisterType((*StopActivityDumpParams)(nil), "api.StopActivityDumpParams")
	proto.RegisterType((*SecurityActivityDumpStoppedMessage)(nil), "api.SecurityActivityDumpStoppedMessage")
	proto.RegisterType((*GenerateProfileParams)(nil), "api.GenerateProfileParams")
	proto.RegisterType((*SecurityProfileGeneratedMessage)(nil), "api.SecurityProfileGeneratedMessage")
	proto.RegisterType((*GenerateGraphParams)(nil), "api.GenerateGraphParams")
	proto.RegisterType((*SecurityGraphGeneratedMessage)(nil), "api.SecurityGraphGeneratedMessage")
	proto.RegisterType((*GetStatusParams)(nil), "api.GetStatusParams")
	proto.RegisterType((*ConstantValueAndSource)(nil), "api.ConstantValueAndSource")
	proto.RegisterType((*SelfTestsStatus)(nil), "api.SelfTestsStatus")
	proto.RegisterType((*Status)(nil), "api.Status")
	proto.RegisterType((*ConstantFetcherStatus)(nil), "api.ConstantFetcherStatus")
	proto.RegisterType((*EnvironmentStatus)(nil), "api.EnvironmentStatus")
}

func init() { proto.RegisterFile("pkg/security/api/api.proto", fileDescriptor_ce049ba84fb5261a) }

var fileDescriptor_ce049ba84fb5261a = []byte{
	// 1333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0xdb, 0x46,
	0x13, 0x95, 0xe4, 0x9f, 0x48, 0xa3, 0xc4, 0xb1, 0x37, 0x8e, 0xc3, 0xd0, 0xc9, 0x17, 0x61, 0x11,
	0x7c, 0x35, 0x8a, 0x20, 0x49, 0x95, 0xa2, 0x08, 0x0a, 0x14, 0x85, 0x23, 0xc9, 0x86, 0x11, 0x3b,
	0x36, 0x28, 0x27, 0x41, 0xd2, 0x8b, 0x62, 0x43, 0xad, 0x24, 0xc2, 0x14, 0x49, 0x2c, 0x97, 0x0e,
	0x72, 0xd1, 0x17, 0xe9, 0xab, 0xb5, 0x37, 0x7d, 0x93, 0x62, 0xff, 0x48, 0x2e, 0x45, 0xa5, 0x45,
	0x2f, 0x04, 0x68, 0x86, 0xb3, 0x67, 0x67, 0x67, 0x0f, 0xcf, 0x0c, 0xc1, 0x4d, 0xae, 0x66, 0xcf,
	0x52, 0xea, 0x67, 0x2c, 0xe0, 0x5f, 0x9e, 0x91, 0x24, 0x10, 0xbf, 0xa7, 0x09, 0x8b, 0x79, 0x8c,
	0xd6, 0x48, 0x12, 0xe0, 0x6d, 0xd8, 0x3a, 0xa6, 0x7c, 0x74, 0x4d, 0x23, 0x7e, 0x41, 0x18, 0x59,
	0xa4, 0x38, 0x81, 0xdd, 0xb1, 0x5e, 0x20, 0xdd, 0x67, 0x34, 0x4d, 0xc9, 0x8c, 0xa2, 0x3d, 0xd8,
	0xf4, 0xb2, 0x90, 0x9e, 0x0c, 0x9d, 0x66, 0xaf, 0x79, 0xd0, 0xf1, 0xb4, 0x85, 0x10, 0xac, 0x0f,
	0x09, 0x27, 0x4e, 0xab, 0xd7, 0x3c, 0xb8, 0xe9, 0xc9, 0xff, 0xc2, 0x77, 0x49, 0x66, 0xa9, 0xb3,
	0xd6, 0x5b, 0x3b, 0xe8, 0x78, 0xf2, 0x3f, 0x72, 0xe0, 0xc6, 0x98, 0xb2, 0xeb, 0xc0, 0xa7, 0xce,
	0xba, 0x04, 0x30, 0x26, 0xbe, 0x07, 0x77, 0x8f, 0x29, 0xbf, 0x60, 0xb1, 0x4f, 0xd3, 0xb4, 0x9c,
	0xca, 0x77, 0xb0, 0x6f, 0x52, 0x29, 0x3f, 0x35, 0x19, 0x99, 0x9d, 0x9b, 0xc5, 0xce, 0xf8, 0x7b,
	0xd8, 0x1b, 0x66, 0x8b, 0x44, 0x87, 0x0f, 0x88, 0x3f, 0xa7, 0x0a, 0x0c, 0xb9, 0xd0, 0x7e, 0x1f,
	0xf0, 0xf9, 0x21, 0x9b, 0xa5, 0x72, 0x45, 0xdb, 0xcb, 0x6d, 0xfc, 0x13, 0x3c, 0x32, 0x1b, 0x55,
	0x57, 0x9b, 0xcd, 0x5c, 0x68, 0x1f, 0x05, 0x21, 0x8d, 0xc8, 0x82, 0xea, 0x02, 0xe4, 0x36, 0x3e,
	0x05, 0x57, 0x2c, 0x7b, 0x43, 0xf9, 0xe7, 0x98, 0x5d, 0xbd, 0x21, 0x0b, 0x9a, 0x26, 0xc4, 0x37,
	0x1b, 0x3f, 0x05, 0x34, 0x8e, 0x48, 0x92, 0xce, 0x63, 0x7e, 0x12, 0x71, 0xca, 0xa6, 0xc4, 0xa7,
	0x26, 0x85, 0x9a, 0x27, 0xf8, 0x37, 0xd8, 0xaf, 0x43, 0x33, 0x89, 0xec, 0xc2, 0x06, 0x65, 0x2c,
	0x66, 0x3a, 0x0b, 0x65, 0x20, 0x0c, 0x37, 0xc5, 0xa2, 0x3c, 0xc5, 0x96, 0x7c, 0x68, 0xf9, 0xd0,
	0x63, 0xb8, 0x75, 0xcc, 0x48, 0x32, 0xcf, 0x83, 0xd6, 0x64, 0x90, 0xed, 0xc4, 0x3b, 0x70, 0xfb,
	0x98, 0xf2, 0x41, 0x1c, 0x4d, 0x83, 0x99, 0xbe, 0x87, 0x5f, 0xe1, 0xae, 0x29, 0x8f, 0xf2, 0x9b,
	0x5c, 0xfe, 0x0f, 0x5b, 0x5e, 0x16, 0xf1, 0x60, 0x41, 0x47, 0x11, 0xf9, 0x14, 0xd2, 0x89, 0x3e,
	0x56, 0xc5, 0x8b, 0xfe, 0x07, 0x70, 0x74, 0x72, 0x66, 0x62, 0x5a, 0x32, 0xa6, 0xe4, 0xc1, 0x77,
	0x60, 0xc7, 0xcb, 0xa2, 0x31, 0x0d, 0xa7, 0x97, 0x34, 0x35, 0xb7, 0xbf, 0x07, 0xbb, 0x1e, 0x0d,
	0x63, 0x32, 0xb9, 0x88, 0xc3, 0xc0, 0x0f, 0x68, 0xaa, 0xfd, 0x0f, 0x61, 0xdf, 0xf6, 0x7b, 0x34,
	0xcd, 0x42, 0xc3, 0x0a, 0x3c, 0x82, 0x87, 0x26, 0x59, 0x03, 0x68, 0x05, 0xa0, 0x2d, 0x68, 0x9d,
	0x5f, 0xe9, 0x44, 0x5b, 0xe7, 0x57, 0xa2, 0xa0, 0x23, 0x59, 0x50, 0x55, 0x33, 0x65, 0xe0, 0x3f,
	0x9b, 0x80, 0x44, 0xf5, 0x0e, 0x7d, 0x1e, 0x5c, 0x0b, 0x02, 0xaa, 0xcb, 0x44, 0xb0, 0xee, 0xc7,
	0x8b, 0x85, 0x2e, 0xbe, 0xfc, 0x2f, 0x98, 0x2d, 0x0e, 0x1b, 0x67, 0x5c, 0x42, 0x6c, 0x78, 0xc6,
	0x44, 0x0f, 0xa0, 0x23, 0x38, 0x26, 0x0b, 0x2c, 0xab, 0xdd, 0xf6, 0x0a, 0x07, 0x7a, 0x02, 0x3b,
	0xc3, 0x60, 0x3a, 0xa5, 0x8c, 0x46, 0x3c, 0x20, 0x9c, 0x4a, 0x6a, 0xae, 0xcb, 0xa8, 0xe5, 0x07,
	0xe8, 0x00, 0x6e, 0x9f, 0x67, 0x3c, 0xc9, 0xf8, 0x30, 0x60, 0xd4, 0xe7, 0x31, 0xfb, 0xe2, 0x6c,
	0xc8, 0x24, 0xaa, 0x6e, 0xc1, 0x05, 0xe5, 0x3a, 0x8a, 0xd9, 0x82, 0x70, 0x67, 0x53, 0x71, 0xa1,
	0xec, 0xc3, 0x7f, 0xb4, 0x8a, 0x77, 0xcb, 0x1c, 0x51, 0x1c, 0xb7, 0x74, 0xb3, 0x3a, 0xde, 0x26,
	0x7d, 0xc5, 0xbb, 0xcc, 0xa9, 0x56, 0x0d, 0xa7, 0x44, 0xd5, 0x06, 0xa2, 0x6a, 0x8a, 0x70, 0xf2,
	0x3f, 0xea, 0x41, 0x77, 0x10, 0x47, 0x9c, 0x04, 0x11, 0x65, 0x27, 0x43, 0xad, 0x09, 0x65, 0x57,
	0xae, 0x22, 0x1b, 0x25, 0x15, 0xb1, 0x2a, 0xba, 0xf9, 0xaf, 0x2a, 0x7a, 0x63, 0x55, 0x45, 0x1d,
	0xb8, 0x71, 0xa9, 0xef, 0xad, 0xad, 0x14, 0x49, 0x9b, 0x82, 0x12, 0x63, 0x4e, 0x18, 0x77, 0x3a,
	0x8a, 0x12, 0xd2, 0x10, 0xf9, 0x9c, 0xd2, 0x29, 0x77, 0x40, 0x9d, 0x42, 0xfc, 0x2f, 0xc8, 0xd3,
	0x2d, 0x93, 0xe7, 0x3e, 0xdc, 0x3b, 0x0d, 0x52, 0x5e, 0x2e, 0xac, 0x61, 0x6f, 0x5c, 0x48, 0x4d,
	0xf9, 0xb1, 0x08, 0x37, 0xb5, 0xff, 0x01, 0x36, 0xe4, 0x0a, 0xa7, 0xd9, 0x5b, 0x3b, 0xe8, 0xf6,
	0x7b, 0x4f, 0x85, 0x66, 0x7f, 0xe5, 0xb2, 0x3c, 0x15, 0xbe, 0x82, 0xc8, 0x4f, 0x60, 0x6f, 0xcc,
	0xe3, 0xa4, 0xbc, 0xae, 0xe0, 0xb2, 0xbc, 0x95, 0x56, 0x71, 0x2b, 0xf8, 0x47, 0xc0, 0x75, 0x3b,
	0x09, 0x84, 0x84, 0x4e, 0x4a, 0x1a, 0x34, 0x2a, 0x6b, 0x90, 0xda, 0x69, 0x20, 0x74, 0x3c, 0xa2,
	0x8c, 0x70, 0x7a, 0xc1, 0xe2, 0x69, 0x10, 0x1a, 0x05, 0xfc, 0x16, 0xb6, 0xcb, 0x60, 0x82, 0x16,
	0x7a, 0xe5, 0x92, 0x1f, 0x7f, 0x28, 0xea, 0xa3, 0x41, 0x0c, 0x66, 0xbe, 0x7b, 0x0f, 0xba, 0x39,
	0x3e, 0x9f, 0x6b, 0xa4, 0xb2, 0x6b, 0x45, 0x25, 0x0e, 0xe1, 0x8e, 0xc1, 0x92, 0x74, 0xf9, 0x0f,
	0xd9, 0x8d, 0x0b, 0x71, 0x91, 0x10, 0x4b, 0xb9, 0x3d, 0x80, 0x8e, 0xc6, 0xce, 0x33, 0x2b, 0x1c,
	0x2b, 0xf2, 0x52, 0x8a, 0x3b, 0xe6, 0x84, 0x67, 0x86, 0x25, 0xef, 0x60, 0x6f, 0x10, 0x47, 0x29,
	0x27, 0x11, 0x7f, 0x47, 0xc2, 0x8c, 0x1e, 0x46, 0x93, 0x71, 0x9c, 0x31, 0x5f, 0xaa, 0x57, 0xde,
	0x82, 0x5b, 0x27, 0x43, 0x01, 0x29, 0x23, 0x24, 0xe4, 0xba, 0xa7, 0x0c, 0xd1, 0xac, 0x55, 0xbc,
	0x7e, 0xe5, 0xb4, 0x85, 0x67, 0x70, 0xdb, 0x88, 0x62, 0xaa, 0x36, 0x14, 0x6f, 0xf0, 0x29, 0x49,
	0xb9, 0xa0, 0x7e, 0xca, 0xc9, 0x22, 0xd1, 0xd8, 0xb6, 0x53, 0x76, 0xef, 0xcc, 0x17, 0x5d, 0xd1,
	0x69, 0xc9, 0xd7, 0xd1, 0x98, 0x22, 0x81, 0x23, 0x12, 0x84, 0xa6, 0xd9, 0x2b, 0x03, 0x5f, 0xc3,
	0xa6, 0xc6, 0x7f, 0x09, 0xdd, 0x51, 0x74, 0x1d, 0xb0, 0x38, 0x5a, 0xd0, 0x88, 0x4b, 0xf4, 0x6e,
	0x7f, 0x4f, 0x72, 0xba, 0xe4, 0x57, 0xc1, 0x5e, 0x39, 0x14, 0xf5, 0xa1, 0x93, 0x27, 0x2b, 0x8f,
	0xd7, 0xed, 0xef, 0xea, 0x77, 0xc1, 0x3a, 0x82, 0x57, 0x84, 0xe1, 0x39, 0xdc, 0x35, 0x85, 0x3b,
	0xa2, 0xdc, 0x9f, 0x53, 0xa6, 0xd3, 0x10, 0xfd, 0x5b, 0x39, 0xd4, 0x7b, 0x25, 0xfa, 0xb7, 0xb6,
	0xd1, 0x0b, 0xd8, 0x94, 0x65, 0x53, 0x67, 0xeb, 0xf6, 0xf7, 0xe5, 0x2e, 0xf5, 0x17, 0xe0, 0xe9,
	0x50, 0xfc, 0x57, 0x13, 0x76, 0x96, 0x0e, 0x20, 0xa7, 0x0c, 0xc2, 0xa2, 0x20, 0x9a, 0xe5, 0xdb,
	0x18, 0x1b, 0xbd, 0x84, 0x8e, 0xc1, 0x34, 0xe7, 0x71, 0xad, 0x9d, 0xac, 0x8c, 0xbd, 0x22, 0x58,
	0xa8, 0xf1, 0x6b, 0xca, 0x22, 0x1a, 0x9e, 0xc6, 0xfe, 0xd5, 0x24, 0xfe, 0x1c, 0xe9, 0x6b, 0xad,
	0x78, 0x45, 0x8f, 0x78, 0x9b, 0xd2, 0xb3, 0x05, 0x49, 0x44, 0x5f, 0x3d, 0x23, 0x89, 0xe9, 0x27,
	0x55, 0xb7, 0xb8, 0xf5, 0xb7, 0x29, 0xf5, 0x82, 0x68, 0xf6, 0x2a, 0x13, 0xba, 0x28, 0x7b, 0x49,
	0xdb, 0xb3, 0x9d, 0xfd, 0xdf, 0xdb, 0xb0, 0x65, 0xf8, 0x7e, 0x16, 0x4f, 0xb2, 0x90, 0xa2, 0x9f,
	0xa1, 0x63, 0x06, 0xc6, 0x14, 0xdd, 0x91, 0xe9, 0xdb, 0x03, 0xa4, 0x7b, 0xdf, 0xd2, 0xab, 0xf2,
	0xc4, 0x86, 0x1b, 0xcf, 0x9b, 0xe8, 0x12, 0xb6, 0x2b, 0xd3, 0x5e, 0x8a, 0x5c, 0x83, 0xb3, 0x3c,
	0x04, 0xba, 0xb6, 0xfc, 0xd5, 0xcc, 0x81, 0x12, 0xf5, 0x3d, 0x6c, 0x57, 0x27, 0x37, 0xa4, 0xae,
	0xb1, 0x7e, 0x1c, 0x74, 0x1f, 0x5b, 0xb0, 0x2b, 0xa6, 0x3e, 0xdc, 0x40, 0xaf, 0xd5, 0x60, 0x65,
	0x94, 0x00, 0xdd, 0xcb, 0x41, 0xed, 0xc9, 0xc0, 0xfd, 0x47, 0x99, 0xc6, 0x0d, 0xf4, 0x01, 0x76,
	0x96, 0xfa, 0x02, 0x7a, 0x20, 0x17, 0xae, 0xe8, 0x17, 0x95, 0x3c, 0x57, 0xb4, 0x0c, 0xdc, 0x40,
	0x1f, 0x61, 0xbb, 0x2a, 0xf3, 0xba, 0x00, 0xf5, 0xea, 0xef, 0x7e, 0xb3, 0x12, 0xd8, 0x16, 0x7b,
	0xdc, 0x40, 0x6f, 0x85, 0x40, 0x59, 0xc2, 0x9e, 0xdf, 0x58, 0x8d, 0xdc, 0x57, 0x52, 0x5e, 0xa1,
	0xe2, 0xb8, 0x81, 0xce, 0xe1, 0x96, 0xa5, 0xc7, 0xc8, 0xb1, 0x40, 0x4b, 0x1a, 0xed, 0x62, 0x0b,
	0xb2, 0x56, 0x7a, 0x71, 0x43, 0x73, 0x53, 0x8d, 0xa8, 0x68, 0xd7, 0x70, 0xaa, 0x3c, 0xca, 0xba,
	0xae, 0x05, 0x64, 0x4d, 0xb3, 0xb8, 0x81, 0x9e, 0x4b, 0x00, 0xfd, 0x2a, 0xe7, 0x00, 0x65, 0x65,
	0x76, 0xbb, 0xba, 0xa6, 0xc2, 0x25, 0xe9, 0xd1, 0x2d, 0x4d, 0xae, 0x48, 0xe9, 0xda, 0xd2, 0x2c,
	0x5b, 0xc9, 0xbf, 0x76, 0x2e, 0x95, 0x05, 0xd9, 0xb2, 0x27, 0x5b, 0xa4, 0xde, 0xa5, 0xba, 0x31,
	0x58, 0xf3, 0xed, 0x6b, 0x93, 0x70, 0x03, 0xfd, 0x02, 0xbb, 0x75, 0x9f, 0x12, 0xe8, 0x51, 0x4e,
	0xe2, 0xfa, 0x6f, 0x16, 0x0d, 0xfe, 0x95, 0xcf, 0x10, 0xdc, 0x78, 0x85, 0x3e, 0x6e, 0x57, 0xbf,
	0x2e, 0x3f, 0x6d, 0xca, 0x4f, 0xcb, 0x17, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x44, 0x11, 0x6a,
	0x13, 0x78, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecurityModuleClient is the client API for SecurityModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecurityModuleClient interface {
	GetEvents(ctx context.Context, in *GetEventParams, opts ...grpc.CallOption) (SecurityModule_GetEventsClient, error)
	GetProcessEvents(ctx context.Context, in *GetProcessEventParams, opts ...grpc.CallOption) (SecurityModule_GetProcessEventsClient, error)
	DumpProcessCache(ctx context.Context, in *DumpProcessCacheParams, opts ...grpc.CallOption) (*SecurityDumpProcessCacheMessage, error)
	DumpActivity(ctx context.Context, in *DumpActivityParams, opts ...grpc.CallOption) (*SecurityActivityDumpMessage, error)
	ListActivityDumps(ctx context.Context, in *ListActivityDumpsParams, opts ...grpc.CallOption) (*SecurityActivityDumpListMessage, error)
	StopActivityDump(ctx context.Context, in *StopActivityDumpParams, opts ...grpc.CallOption) (*SecurityActivityDumpStoppedMessage, error)
	GenerateProfile(ctx context.Context, in *GenerateProfileParams, opts ...grpc.CallOption) (*SecurityProfileGeneratedMessage, error)
	GenerateGraph(ctx context.Context, in *GenerateGraphParams, opts ...grpc.CallOption) (*SecurityGraphGeneratedMessage, error)
	GetConfig(ctx context.Context, in *GetConfigParams, opts ...grpc.CallOption) (*SecurityConfigMessage, error)
	GetStatus(ctx context.Context, in *GetStatusParams, opts ...grpc.CallOption) (*Status, error)
	RunSelfTest(ctx context.Context, in *RunSelfTestParams, opts ...grpc.CallOption) (*SecuritySelfTestResultMessage, error)
	ReloadPolicies(ctx context.Context, in *ReloadPoliciesParams, opts ...grpc.CallOption) (*ReloadPoliciesResultMessage, error)
	DumpNetworkNamespace(ctx context.Context, in *DumpNetworkNamespaceParams, opts ...grpc.CallOption) (*DumpNetworkNamespaceMessage, error)
}

type securityModuleClient struct {
	cc *grpc.ClientConn
}

func NewSecurityModuleClient(cc *grpc.ClientConn) SecurityModuleClient {
	return &securityModuleClient{cc}
}

func (c *securityModuleClient) GetEvents(ctx context.Context, in *GetEventParams, opts ...grpc.CallOption) (SecurityModule_GetEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SecurityModule_serviceDesc.Streams[0], "/api.SecurityModule/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &securityModuleGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SecurityModule_GetEventsClient interface {
	Recv() (*SecurityEventMessage, error)
	grpc.ClientStream
}

type securityModuleGetEventsClient struct {
	grpc.ClientStream
}

func (x *securityModuleGetEventsClient) Recv() (*SecurityEventMessage, error) {
	m := new(SecurityEventMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *securityModuleClient) GetProcessEvents(ctx context.Context, in *GetProcessEventParams, opts ...grpc.CallOption) (SecurityModule_GetProcessEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SecurityModule_serviceDesc.Streams[1], "/api.SecurityModule/GetProcessEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &securityModuleGetProcessEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SecurityModule_GetProcessEventsClient interface {
	Recv() (*SecurityProcessEventMessage, error)
	grpc.ClientStream
}

type securityModuleGetProcessEventsClient struct {
	grpc.ClientStream
}

func (x *securityModuleGetProcessEventsClient) Recv() (*SecurityProcessEventMessage, error) {
	m := new(SecurityProcessEventMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *securityModuleClient) DumpProcessCache(ctx context.Context, in *DumpProcessCacheParams, opts ...grpc.CallOption) (*SecurityDumpProcessCacheMessage, error) {
	out := new(SecurityDumpProcessCacheMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpProcessCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) DumpActivity(ctx context.Context, in *DumpActivityParams, opts ...grpc.CallOption) (*SecurityActivityDumpMessage, error) {
	out := new(SecurityActivityDumpMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) ListActivityDumps(ctx context.Context, in *ListActivityDumpsParams, opts ...grpc.CallOption) (*SecurityActivityDumpListMessage, error) {
	out := new(SecurityActivityDumpListMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/ListActivityDumps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) StopActivityDump(ctx context.Context, in *StopActivityDumpParams, opts ...grpc.CallOption) (*SecurityActivityDumpStoppedMessage, error) {
	out := new(SecurityActivityDumpStoppedMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/StopActivityDump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) GenerateProfile(ctx context.Context, in *GenerateProfileParams, opts ...grpc.CallOption) (*SecurityProfileGeneratedMessage, error) {
	out := new(SecurityProfileGeneratedMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/GenerateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) GenerateGraph(ctx context.Context, in *GenerateGraphParams, opts ...grpc.CallOption) (*SecurityGraphGeneratedMessage, error) {
	out := new(SecurityGraphGeneratedMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/GenerateGraph", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) GetConfig(ctx context.Context, in *GetConfigParams, opts ...grpc.CallOption) (*SecurityConfigMessage, error) {
	out := new(SecurityConfigMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) GetStatus(ctx context.Context, in *GetStatusParams, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) RunSelfTest(ctx context.Context, in *RunSelfTestParams, opts ...grpc.CallOption) (*SecuritySelfTestResultMessage, error) {
	out := new(SecuritySelfTestResultMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/RunSelfTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) ReloadPolicies(ctx context.Context, in *ReloadPoliciesParams, opts ...grpc.CallOption) (*ReloadPoliciesResultMessage, error) {
	out := new(ReloadPoliciesResultMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/ReloadPolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) DumpNetworkNamespace(ctx context.Context, in *DumpNetworkNamespaceParams, opts ...grpc.CallOption) (*DumpNetworkNamespaceMessage, error) {
	out := new(DumpNetworkNamespaceMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpNetworkNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityModuleServer is the server API for SecurityModule service.
type SecurityModuleServer interface {
	GetEvents(*GetEventParams, SecurityModule_GetEventsServer) error
	GetProcessEvents(*GetProcessEventParams, SecurityModule_GetProcessEventsServer) error
	DumpProcessCache(context.Context, *DumpProcessCacheParams) (*SecurityDumpProcessCacheMessage, error)
	DumpActivity(context.Context, *DumpActivityParams) (*SecurityActivityDumpMessage, error)
	ListActivityDumps(context.Context, *ListActivityDumpsParams) (*SecurityActivityDumpListMessage, error)
	StopActivityDump(context.Context, *StopActivityDumpParams) (*SecurityActivityDumpStoppedMessage, error)
	GenerateProfile(context.Context, *GenerateProfileParams) (*SecurityProfileGeneratedMessage, error)
	GenerateGraph(context.Context, *GenerateGraphParams) (*SecurityGraphGeneratedMessage, error)
	GetConfig(context.Context, *GetConfigParams) (*SecurityConfigMessage, error)
	GetStatus(context.Context, *GetStatusParams) (*Status, error)
	RunSelfTest(context.Context, *RunSelfTestParams) (*SecuritySelfTestResultMessage, error)
	ReloadPolicies(context.Context, *ReloadPoliciesParams) (*ReloadPoliciesResultMessage, error)
	DumpNetworkNamespace(context.Context, *DumpNetworkNamespaceParams) (*DumpNetworkNamespaceMessage, error)
}

// UnimplementedSecurityModuleServer can be embedded to have forward compatible implementations.
type UnimplementedSecurityModuleServer struct {
}

func (*UnimplementedSecurityModuleServer) GetEvents(req *GetEventParams, srv SecurityModule_GetEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedSecurityModuleServer) GetProcessEvents(req *GetProcessEventParams, srv SecurityModule_GetProcessEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetProcessEvents not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpProcessCache(ctx context.Context, req *DumpProcessCacheParams) (*SecurityDumpProcessCacheMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpProcessCache not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpActivity(ctx context.Context, req *DumpActivityParams) (*SecurityActivityDumpMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpActivity not implemented")
}
func (*UnimplementedSecurityModuleServer) ListActivityDumps(ctx context.Context, req *ListActivityDumpsParams) (*SecurityActivityDumpListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActivityDumps not implemented")
}
func (*UnimplementedSecurityModuleServer) StopActivityDump(ctx context.Context, req *StopActivityDumpParams) (*SecurityActivityDumpStoppedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopActivityDump not implemented")
}
func (*UnimplementedSecurityModuleServer) GenerateProfile(ctx context.Context, req *GenerateProfileParams) (*SecurityProfileGeneratedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateProfile not implemented")
}
func (*UnimplementedSecurityModuleServer) GenerateGraph(ctx context.Context, req *GenerateGraphParams) (*SecurityGraphGeneratedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateGraph not implemented")
}
func (*UnimplementedSecurityModuleServer) GetConfig(ctx context.Context, req *GetConfigParams) (*SecurityConfigMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (*UnimplementedSecurityModuleServer) GetStatus(ctx context.Context, req *GetStatusParams) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedSecurityModuleServer) RunSelfTest(ctx context.Context, req *RunSelfTestParams) (*SecuritySelfTestResultMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSelfTest not implemented")
}
func (*UnimplementedSecurityModuleServer) ReloadPolicies(ctx context.Context, req *ReloadPoliciesParams) (*ReloadPoliciesResultMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadPolicies not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpNetworkNamespace(ctx context.Context, req *DumpNetworkNamespaceParams) (*DumpNetworkNamespaceMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpNetworkNamespace not implemented")
}

func RegisterSecurityModuleServer(s *grpc.Server, srv SecurityModuleServer) {
	s.RegisterService(&_SecurityModule_serviceDesc, srv)
}

func _SecurityModule_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityModuleServer).GetEvents(m, &securityModuleGetEventsServer{stream})
}

type SecurityModule_GetEventsServer interface {
	Send(*SecurityEventMessage) error
	grpc.ServerStream
}

type securityModuleGetEventsServer struct {
	grpc.ServerStream
}

func (x *securityModuleGetEventsServer) Send(m *SecurityEventMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _SecurityModule_GetProcessEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetProcessEventParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityModuleServer).GetProcessEvents(m, &securityModuleGetProcessEventsServer{stream})
}

type SecurityModule_GetProcessEventsServer interface {
	Send(*SecurityProcessEventMessage) error
	grpc.ServerStream
}

type securityModuleGetProcessEventsServer struct {
	grpc.ServerStream
}

func (x *securityModuleGetProcessEventsServer) Send(m *SecurityProcessEventMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _SecurityModule_DumpProcessCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpProcessCacheParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpProcessCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpProcessCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpProcessCache(ctx, req.(*DumpProcessCacheParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_DumpActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpActivityParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpActivity(ctx, req.(*DumpActivityParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_ListActivityDumps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivityDumpsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).ListActivityDumps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/ListActivityDumps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).ListActivityDumps(ctx, req.(*ListActivityDumpsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_StopActivityDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopActivityDumpParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).StopActivityDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/StopActivityDump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).StopActivityDump(ctx, req.(*StopActivityDumpParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_GenerateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateProfileParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).GenerateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/GenerateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).GenerateProfile(ctx, req.(*GenerateProfileParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_GenerateGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateGraphParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).GenerateGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/GenerateGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).GenerateGraph(ctx, req.(*GenerateGraphParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).GetConfig(ctx, req.(*GetConfigParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).GetStatus(ctx, req.(*GetStatusParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_RunSelfTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSelfTestParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).RunSelfTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/RunSelfTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).RunSelfTest(ctx, req.(*RunSelfTestParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_ReloadPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPoliciesParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).ReloadPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/ReloadPolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).ReloadPolicies(ctx, req.(*ReloadPoliciesParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_DumpNetworkNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpNetworkNamespaceParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpNetworkNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpNetworkNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpNetworkNamespace(ctx, req.(*DumpNetworkNamespaceParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecurityModule_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SecurityModule",
	HandlerType: (*SecurityModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DumpProcessCache",
			Handler:    _SecurityModule_DumpProcessCache_Handler,
		},
		{
			MethodName: "DumpActivity",
			Handler:    _SecurityModule_DumpActivity_Handler,
		},
		{
			MethodName: "ListActivityDumps",
			Handler:    _SecurityModule_ListActivityDumps_Handler,
		},
		{
			MethodName: "StopActivityDump",
			Handler:    _SecurityModule_StopActivityDump_Handler,
		},
		{
			MethodName: "GenerateProfile",
			Handler:    _SecurityModule_GenerateProfile_Handler,
		},
		{
			MethodName: "GenerateGraph",
			Handler:    _SecurityModule_GenerateGraph_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _SecurityModule_GetConfig_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _SecurityModule_GetStatus_Handler,
		},
		{
			MethodName: "RunSelfTest",
			Handler:    _SecurityModule_RunSelfTest_Handler,
		},
		{
			MethodName: "ReloadPolicies",
			Handler:    _SecurityModule_ReloadPolicies_Handler,
		},
		{
			MethodName: "DumpNetworkNamespace",
			Handler:    _SecurityModule_DumpNetworkNamespace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _SecurityModule_GetEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetProcessEvents",
			Handler:       _SecurityModule_GetProcessEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/security/api/api.proto",
}
